name = "knkpart"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "knkpart-db"
database_id = "34f14d8d-b16a-41c1-86b0-7426139ef5ea"  # APAC region - สร้าง 2026-09-17